site_name: Winterbloom Big Honking Button User Guide
copyright: "Â© 2020 Winterbloom, licensed under Creative Commons CC BY-SA 4.0"
repo_url: "https://github.com/theacodes/Winterbloom-Big-Honking-Button"
edit_uri: edit/master/user_guide/docs
theme:
  name: cinder
  hljs_languages:
  - python
extra_css:
  - "css/overrides.css"
markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: "#"
      toc_depth: 2
nav:
  - "User Guide": index.md